[package]
name = "hyperparameter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hyperparameter"
crate-type = ["cdylib"]

[dependencies]
arraystring = "0.3.0"
pyo3 = { version = "0.18.1", features = [
    "extension-module",
    "abi3",
    "abi3-py37",
] }

[dev_dependencies]
rspec = "1.0"
